apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecd
  namespace: kubecd
  labels:
    app: kubecd
    tier: daemon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubecd
      tier: daemon
  template:
    metadata:
      labels:
        app: kubecd
        tier: daemon
    spec:
      containers:
      - name: kubecd
        image: sixteenbitt/kubecd:latest
        ports:
        - containerPort: 8000
